export enum EKey {
    albumsPageSize = 'albumsPageSize',
    albumsPage = 'albumsPage',
    commentsPageSize = 'commentsPageSize',
    commentsPage = 'commentsPage',
    photosPageSize = 'photosPageSize',
    photosPage = 'photosPage',
    postsPageSize = 'postsPageSize',
    postsPage = 'postsPage',
    todosPageSize = 'todosPageSize',
    todosPage = 'todosPage',
    usersPageSize = 'usersPageSize',
    usersPage = 'usersPage',
    selectedAlbum = 'selectedAlbum',
    selectedComment = 'selectedComment',
    selectedPhoto = 'selectedPhoto',
    selectedPost = 'selectedPost',
    selectedTodo = 'selectedTodo',
    selectedUser = 'selectedUser',
}