import { ERarity } from '../enums/rarity.enum';
import { IBlock } from '../interfaces/block.interface';
import { EClass } from '../enums/class';

export const Blocks: IBlock[] = [
    {
        id: 1,
        name: 'Ancient Holy Grail',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/7/7a/Antique_Normal_Ancient_Holy_Grail.png',
        value: 120,
        width: 62,
        height: 128,
        space: 2
    },
    {
        id: 2,
        name: 'Ancient Holy Grail',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/7/7e/Antique_Rare_Ancient_Holy_Grail.png',
        value: 210,
        width: 62,
        height: 128,
        space: 2
    },
    {
        id: 3,
        name: 'Boulder Staff',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/2/2a/Antique_Normal_Boulder_Staff.png',
        value: 400,
        width: 194,
        height: 128,
        space: 4
    },
    {
        id: 4,
        name: 'Boulder Staff',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/2/22/Antique_Rare_Boulder_Staff.png',
        value: 600,
        width: 194,
        height: 128,
        space: 4
    },
    {
        id: 5,
        name: 'Cadian Goblet',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/2/23/Antique_Normal_Cadian_Goblet.png',
        value: 300,
        width: 128,
        height: 128,
        space: 3
    },
    {
        id: 6,
        name: 'Cadian Goblet',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/4/44/Antique_Rare_Cadian_Goblet.png',
        value: 450,
        width: 128,
        height: 128,
        space: 3
    },
    {
        id: 7,
        name: 'Exorcism Ring',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/9/93/Antique_Normal_Exorcism_Ring.png',
        value: 30,
        width: 62,
        height: 62,
        space: 1
    },
    {
        id: 8,
        name: 'Exorcism Ring',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/8/89/Antique_Rare_Exorcism_Ring.png',
        value: 45,
        width: 62,
        height: 62,
        space: 1
    },
    {
        id: 9,
        name: 'Gilded Sacred Lamp',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/5/53/Antique_Normal_Gilded_Sacred_Lamp.png',
        value: 300,
        width: 128,
        height: 128,
        space: 3
    },
    {
        id: 10,
        name: 'Gilded Sacred Lamp',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/b/ba/Antique_Rare_Gilded_Sacred_Lamp.png',
        value: 450,
        width: 128,
        height: 128,
        space: 3
    },
    {
        id: 11,
        name: 'Gleaming Earrings',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/4/4d/Antique_Normal_Gleaming_Earrings.png',
        value: 40,
        width: 62,
        height: 62,
        space: 1
    },
    {
        id: 12,
        name: 'Gleaming Earrings',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/a/a2/Antique_Rare_Gleaming_Earrings.png',
        value: 60,
        width: 62,
        height: 62,
        space: 1
    },
    {
        id: 13,
        name: 'Lakeside Harp',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/7/7f/Antique_Normal_Lakeside_Harp.png',
        value: 550,
        width: 128,
        height: 194,
        space: 5
    },
    {
        id: 14,
        name: 'Lakeside Harp',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/0/01/Antique_Rare_Lakeside_Harp.png',
        value: 825,
        width: 128,
        height: 194,
        space: 5
    },
    {
        id: 15,
        name: 'Luminescent Lamp',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/c/c0/Antique_Normal_Luminescent_Lamp.png',
        value: 400,
        width: 128,
        height: 194,
        space: 4
    },
    {
        id: 16,
        name: 'Luminescent Lamp',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/f/f7/Antique_Rare_Luminescent_Lamp.png',
        value: 600,
        width: 128,
        height: 194,
        space: 4
    },
    {
        id: 17,
        name: 'Monastery Pot',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/b/b9/Antique_Normal_Monastery_Pot.png',
        value: 400,
        width: 128,
        height: 194,
        space: 4
    },
    {
        id: 18,
        name: 'Monastery Pot',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/e/e9/Antique_Rare_Monastery_Pot.png',
        value: 600,
        width: 128,
        height: 194,
        space: 4
    },
    {
        id: 19,
        name: 'Relic Hourglass',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/3/38/Antique_Normal_Relic_Hourglass.png',
        value: 180,
        width: 62,
        height: 128,
        space: 2
    },
    {
        id: 20,
        name: 'Relic Hourglass',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/3/36/Antique_Rare_Relic_Hourglass.png',
        value: 270,
        width: 62,
        height: 128,
        space: 2
    },
    {
        id: 21,
        name: 'Ritual Porcelain',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/d/de/Antique_Normal_Ritual_Porcelain.png',
        value: 180,
        width: 128,
        height: 62,
        space: 2
    },
    {
        id: 22,
        name: 'Ritual Porcelain',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/a/a2/Antique_Rare_Ritual_Porcelain.png',
        value: 270,
        width: 128,
        height: 62,
        space: 2
    },
    {
        id: 23,
        name: 'Wasteland Horn',
        rarity: ERarity.NORMAL,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/f/fc/Antique_Normal_Wasteland_Horn.png',
        value: 300,
        width: 128,
        height: 128,
        space: 3
    },
    {
        id: 24,
        name: 'Wasteland Horn',
        rarity: ERarity.RARE,
        class: EClass.ANTIQUE,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/0/06/Antique_Rare_Wasteland_Horn.png',
        value: 450,
        width: 128,
        height: 128,
        space: 3
    },
    {
        id: 25,
        name: 'Anglerfish',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/7/76/Food_Normal_Anglerfish.png',
        value: 550,
        width: 194,
        height: 128,
        space: 5
    },
    {
        id: 26,
        name: 'Anglerfish',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/9/99/Food_Rare_Anglerfish.png',
        value: 825,
        width: 194,
        height: 128,
        space: 5
    },
    {
        id: 27,
        name: 'Blue Fire Prawn',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/3/3b/Food_Normal_Blue_Fire_Prawn.png',
        value: 300,
        width: 128,
        height: 128,
        space: 3
    },
    {
        id: 28,
        name: 'Blue Fire Prawn',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/9/95/Food_Rare_Blue_Fire_Prawn.png',
        value: 450,
        width: 128,
        height: 128,
        space: 3
    },
    {
        id: 29,
        name: 'Coldwater Octopus',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/2/2b/Food_Normal_Coldwater_Octopus.png',
        value: 700,
        width: 194,
        height: 194,
        space: 6
    },
    {
        id: 30,
        name: 'Coldwater Octopus',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/9/9f/Food_Rare_Coldwater_Octopus.png',
        value: 1050,
        width: 194,
        height: 194,
        space: 6
    },
    {
        id: 31,
        name: 'Flying Fish',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/8/8d/Food_Normal_Flying_Fish.png',
        value: 550,
        width: 194,
        height: 194,
        space: 5
    },
    {
        id: 32,
        name: 'Flying Fish',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/3/3f/Food_Rare_Flying_Fish.png',
        value: 825,
        width: 194,
        height: 194,
        space: 5
    },
    {
        id: 33,
        name: 'King Crab',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/a/a2/Food_Normal_King_Crab.png',
        value: 900,
        width: 194,
        height: 194,
        space: 7
    },
    {
        id: 34,
        name: 'King Crab',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/7/77/Food_Rare_King_Crab.png',
        value: 1350,
        width: 194,
        height: 194,
        space: 7
    },
    {
        id: 35,
        name: 'Late Summer Eel',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/9/9f/Food_Normal_Late_Summer_Eel.png',
        value: 400,
        width: 194,
        height: 128,
        space: 4
    },
    {
        id: 36,
        name: 'Late Summer Eel',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/1/1b/Food_Rare_Late_Summer_Eel.png',
        value: 600,
        width: 194,
        height: 128,
        space: 4
    },
    {
        id: 37,
        name: 'Manta Ray',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/5/50/Food_Normal_Manta_Ray.png',
        value: 900,
        width: 194,
        height: 194,
        space: 7
    },
    {
        id: 38,
        name: 'Manta Ray',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/5/57/Food_Rare_Manta_Ray.png',
        value: 1350,
        width: 194,
        height: 194,
        space: 7
    },
    {
        id: 39,
        name: 'Northern Vale Cutlassfish',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/1/17/Food_Normal_Northern_Vale_Cutlassfish.png',
        value: 700,
        width: 194,
        height: 194,
        space: 6
    },
    {
        id: 40,
        name: 'Northern Vale Cutlassfish',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/b/be/Food_Rare_Northern_Vale_Cutlassfish.png',
        value: 1050,
        width: 194,
        height: 194,
        space: 6
    },
    {
        id: 41,
        name: 'Onion',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/b/b1/Food_Normal_Onion.png',
        value: 80,
        width: 62,
        height: 62,
        space: 1
    },
    {
        id: 42,
        name: 'Onion',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/a/a8/Food_Rare_Onion.png',
        value: 120,
        width: 62,
        height: 62,
        space: 1
    },
    {
        id: 43,
        name: 'Queen Lobster',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/8/84/Food_Normal_Queen_Lobster.png',
        value: 400,
        width: 194,
        height: 128,
        space: 4
    },
    {
        id: 44,
        name: 'Queen Lobster',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/4/4c/Food_Rare_Queen_Lobster.png',
        value: 600,
        width: 194,
        height: 128,
        space: 4
    },
    {
        id: 45,
        name: 'Radish',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/3/3c/Food_Normal_Radish.png',
        value: 90,
        width: 128,
        height: 62,
        space: 2
    },
    {
        id: 46,
        name: 'Radish',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/7/72/Food_Rare_Radish.png',
        value: 135,
        width: 128,
        height: 62,
        space: 2
    },
    {
        id: 47,
        name: 'Sugar Cane',
        rarity: ERarity.NORMAL,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/d/d4/Food_Normal_Sugarcane.png',
        value: 300,
        width: 194,
        height: 62,
        space: 3
    },
    {
        id: 48,
        name: 'Sugar Cane',
        rarity: ERarity.RARE,
        class: EClass.FOOD,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/4/4a/Food_Rare_Sugarcane.png',
        value: 450,
        width: 194,
        height: 62,
        space: 3
    },
    {
        id: 49,
        name: 'Academy Armor',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/3/3d/Weapon_Normal_Academy_Armor.png',
        value: 700,
        width: 128,
        height: 194,
        space: 6
    },
    {
        id: 50,
        name: 'Academy Armor',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/9/97/Weapon_Rare_Academy_Armor.png',
        value: 1050,
        width: 128,
        height: 194,
        space: 6
    },
    {
        id: 51,
        name: 'Akakage Shuriken',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/1/1a/Weapon_Normal_Akakage_Shuriken.png',
        value: 550,
        width: 194,
        height: 194,
        space: 5
    },
    {
        id: 52,
        name: 'Akakage Shuriken',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/3/39/Weapon_Rare_Akakage_Shuriken.png',
        value: 825,
        width: 194,
        height: 194,
        space: 5
    },
    {
        id: 53,
        name: 'Boulder Belt',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/9/97/Weapon_Normal_Boulder_Belt.png',
        value: 180,
        width: 128,
        height: 62,
        space: 2
    },
    {
        id: 54,
        name: 'Boulder Belt',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/c/ce/Weapon_Rare_Boulder_Belt.png',
        value: 270,
        width: 128,
        height: 62,
        space: 2
    },
    {
        id: 55,
        name: 'Demon\'s Scythe',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/b/b7/Weapon_Normal_Demon%27s_Scythe.png',
        value: 200,
        width: 128,
        height: 194,
        space: 4
    },
    {
        id: 56,
        name: 'Demon\'s Scythe',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/b/bd/Weapon_Rare_Demon%27s_Scythe.png',
        value: 300,
        width: 128,
        height: 194,
        space: 4
    },
    {
        id: 57,
        name: 'Explosive Meteor Hammer',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/2/22/Weapon_Normal_Explosive_Meteor_Hammer.png',
        value: 700,
        width: 194,
        height: 194,
        space: 6
    },
    {
        id: 58,
        name: 'Explosive Meteor Hammer',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/f/f3/Weapon_Rare_Explosive_Meteor_Hammer.png',
        value: 1050,
        width: 194,
        height: 194,
        space: 6
    },
    {
        id: 59,
        name: 'Flamewind Scimitar',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/9/92/Weapon_Normal_Flamewind_Scimitar.png',
        value: 400,
        width: 128,
        height: 194,
        space: 4
    },
    {
        id: 60,
        name: 'Flamewind Scimitar',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/b/ba/Weapon_Rare_Flamewind_Scimitar.png',
        value: 600,
        width: 128,
        height: 194,
        space: 4
    },
    {
        id: 61,
        name: 'Knight\'s Shield',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/c/c8/Weapon_Normal_Knight%27s_Shield.png',
        value: 400,
        width: 128,
        height: 128,
        space: 4
    },
    {
        id: 62,
        name: 'Knight\'s Shield',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/8/8d/Weapon_Rare_Knight%27s_Shield.png',
        value: 600,
        width: 128,
        height: 128,
        space: 4
    },
    {
        id: 63,
        name: 'Moniyan Lance',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/8/8e/Weapon_Normal_Moniyan_Lance.png',
        value: 300,
        width: 62,
        height: 194,
        space: 3
    },
    {
        id: 64,
        name: 'Moniyan Lance',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/7/76/Weapon_Rare_Moniyan_Lance.png',
        value: 450,
        width: 62,
        height: 194,
        space: 3
    },
    {
        id: 65,
        name: 'Northern Vale Hammer',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/1/12/Weapon_Normal_Northern_Vale_Hammer.png',
        value: 550,
        width: 194,
        height: 128,
        space: 5
    },
    {
        id: 66,
        name: 'Northern Vale Hammer',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/6/65/Weapon_Rare_Northern_Vale_Hammer.png',
        value: 825,
        width: 194,
        height: 128,
        space: 5
    },
    {
        id: 67,
        name: 'Plains Boots',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/f/f7/Weapon_Normal_Plains_Boots.png',
        value: 300,
        width: 128,
        height: 128,
        space: 3
    },
    {
        id: 68,
        name: 'Plains Boots',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/6/62/Weapon_Rare_Plains_Boots.png',
        value: 450,
        width: 128,
        height: 128,
        space: 3
    },
    {
        id: 69,
        name: 'Silvermoon Bow & Arrows',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/4/43/Weapon_Normal_Silvermoon_Bow_%26_Arrows.png',
        value: 400,
        width: 194,
        height: 128,
        space: 4
    },
    {
        id: 70,
        name: 'Silvermoon Bow & Arrows',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/6/63/Weapon_Rare_Silvermoon_Bow_%26_Arrows.png',
        value: 600,
        width: 194,
        height: 128,
        space: 4
    },
    {
        id: 71,
        name: 'Stream Dagger',
        rarity: ERarity.NORMAL,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/5/54/Weapon_Normal_Stream_Dagger.png',
        value: 180,
        width: 62,
        height: 128,
        space: 2
    },
    {
        id: 72,
        name: 'Stream Dagger',
        rarity: ERarity.RARE,
        class: EClass.WEAPON,
        image: 'https://static.wikia.nocookie.net/mobile-legends-adventure/images/d/d1/Weapon_Rare_Stream_Dagger.png',
        value: 280,
        width: 62,
        height: 128,
        space: 2
    }
];